name: biweekly-external-link-check
on:
  # schedule: Disable schedule fail for now
  # At 6:05 AM -0500, every two weeks strictly check all external links (301 Moved is a failure not just a warning)
  #  - cron: '05 11 */14 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-unminified-site:
    runs-on: ubuntu-20.04
    steps:
      - name: "Build Site with Hugo and Audit"
        uses: danielfdickinson/build-audit-action-hugo-dfd@main
        with:
          source-directory: exampleSite
          upload-site-as: unminified-site
          use-lfs: false
  check-external-links:
    needs: build-unminified-site
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run DFD Hugo Check Links
        uses: ./
        with:
          canonical-root: https://www.example.com/
          check-external: true
          check-external-strict: true
          upload-logs-as: test-logs
          upload-logs-retention: 1
