name: monthly-external-link-check
on:
  schedule:
    # At 6:05 AM -0500 on the 25th day of month strictly check all external links (301 Moved is a failure not just a warning)
    - cron: '05 11 25 * *'
jobs:
  build-unminified-site:
    runs-on: ubuntu-20.04
    steps:
      - name: "Build Site with Hugo and Audit"
        uses: danielfdickinson/build-audit-action-hugo-dfd@v0.1.0
        with:
          source-directory: src
          upload-site-as: unminified-site
          use-lfs: false
  check-external-links:
    needs: build-unminified-site
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run DFD Hugo Check Links
        uses: ./
        with:
          canonical-root: https://www.example.com/
          check-external: true
          check-external-strict: true
          upload-logs-as: test-logs
          upload-logs-retention: 1
